### ISSUE TITLE
Start overlay without using hotkey kebyind? 

### ISSUE THREAD

**Issue by masudhossain** [hiitiger/gelectron#27]
I want' to execute overlay.toggle without using the hotkey, is this possible? Having issues with getting this to work with games like Overwatch and League of Legends

**Comment by hiitiger** [comment]
yeah you can call overlay.toggle to turn on/off any time.
I haven't played Overwatch since a long time ago.
If hotkey has issues with some game, you can try to define MACRO HOTKEY_THREADED for n_overlay project (#define HOTKEY_THREADED  in stable.h for example) and try again.
But again for some game (especially some EA's game) input intercepting is not quite handled well now

**Comment by masudhossain** [comment]
@hiitiger so `overlay.toggle()`? Wouldn't that give it a overlay not defined error? 

My code for this: 
![Screenshot_7](https://user-images.githubusercontent.com/16615124/67802573-ca0afc00-fa61-11e9-821a-930db0b96764.png)

**Comment by masudhossain** [comment]
Did some additional testing and it seems Overwatch specifically has issues with overlays working with them. Not sure why, but I know Discord has issues with it too and is list of problematic games.
